WIP: Add matrix notification task
okd-project/okd-release-pipeline pull request #2
Opened 2023-03-29 14:35 UTC by sherine-k

2023-03-30 09:17 UTC, aguidirh requested changes
Well done @sherine-k, looking forward to see the matrix working in our pipelines.

2023-03-30 13:47 UTC, aguidirh approved these changes
Very good improvement adding kustomization to this repository. Thank you @sherine-k

2023-03-30 13:47 UTC, aguidirh commented on README.md
> +tkn pipeline start okd-release-pipeline --param release-controller="https://origin-release.ci.openshift.org" --param release-stream="4.13.0-0.okd-scos" --param release-imagestream="release-scos-next"
Thanks for adding both release-imagestream @sherine-k

2023-04-14 15:54 UTC, sherine-k commented
This has been tested on operate first and now sends a message to  #okd:fedoraproject.org as `okd-bot`

2023-04-28 12:19 UTC, aguidirh commented
/lgtm

2023-04-28 12:19 UTC, merged